sudo: required
services:
  - docker

before_install:
  - docker build -t ostinlviv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ostinlviv/react-test npm run test -- --coverage

after_success:
  - docker build -t ostinlviv/multi-client ./client
  - docker build -t ostinlviv/multi-nginx ./nginx
  - docker build -t ostinlviv/multi-server ./server
  - docker build -t ostinlviv/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ostinlviv/multi-client
  - docker push ostinlviv/multi-nginx
  - docker push ostinlviv/multi-server
  - docker push ostinlviv/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-491362138747
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"